import json
from pathlib import Path


INPUT_PATH = Path("prepared_task4_with_context.jsonl")

TRAIN_BASE_PATH = Path("data/task4_train.jsonl")
VAL_BASE_PATH = Path("data/task4_val.jsonl")

TRAIN_OUTPUT_PATH = Path("data/task4_train_context.jsonl")
VAL_OUTPUT_PATH = Path("data/task4_val_context.jsonl")


MAX_CONTEXT_CHARS = 6000


def load_jsonl(path: Path):
    items = []

    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                items.append(json.loads(line))

    return items


def save_jsonl(path: Path, items):
    path.parent.mkdir(exist_ok=True)

    with open(path, "w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")


def truncate_text(text: str, max_chars: int) -> str:
    if len(text) <= max_chars:
        return text

    return text[:max_chars].rstrip() + "\n...[context truncated]"


def build_prompt(item):
    research_question = item["research_question"]
    query_id = item["query_id"]
    previous_queries = item.get("previous_queries", [])
    visited_context = truncate_text(item.get("visited_context", ""), MAX_CONTEXT_CHARS)

    if previous_queries:
        previous_queries_text = "\n".join(
            f"{i + 1}. {query}" for i, query in enumerate(previous_queries)
        )
    else:
        previous_queries_text = "No previous queries."

    prompt = f"""You are a search-query planner for a DeepResearch agent.

The agent investigates a complex research question step by step.
You are given:
1. The original research question.
2. Web sources that have already been visited.
3. Previous search queries generated by the agent.

Your task is to generate exactly one next search query.

The next query should:
- explore a useful missing aspect of the research question;
- use concrete technical terms from the visited sources when helpful;
- avoid repeating previous queries;
- avoid simply restating the research question;
- be suitable for web search or academic search;
- be concise, usually 7-18 words;
- return only the query, without explanation.

Research question:
{research_question}

Current query step:
{query_id}

Visited sources context:
{visited_context}

Previous generated queries:
{previous_queries_text}

Next search query:"""

    return prompt


def main():
    all_items = load_jsonl(INPUT_PATH)

    train_base = load_jsonl(TRAIN_BASE_PATH)
    val_base = load_jsonl(VAL_BASE_PATH)

    train_questions = set(item["research_question"] for item in train_base)
    val_questions = set(item["research_question"] for item in val_base)

    train_items = []
    val_items = []

    for item in all_items:
        item = item.copy()
        item["prompt"] = build_prompt(item)

        if item["research_question"] in val_questions:
            val_items.append(item)
        elif item["research_question"] in train_questions:
            train_items.append(item)
        else:
            raise ValueError(f"Unknown research question: {item['research_question']}")

    save_jsonl(TRAIN_OUTPUT_PATH, train_items)
    save_jsonl(VAL_OUTPUT_PATH, val_items)

    print("Saved train:", TRAIN_OUTPUT_PATH)
    print("Saved val:", VAL_OUTPUT_PATH)
    print("Train examples:", len(train_items))
    print("Val examples:", len(val_items))

    print()
    print("Validation questions:")
    for question in sorted(val_questions):
        print("-", question[:180])

    print()
    print("Prompt preview:")
    print(val_items[0]["prompt"][:2500])


if __name__ == "__main__":
    main()