import json
from pathlib import Path


INPUT_PATH = Path("prepared_task4_with_context.jsonl")

TRAIN_BASE_PATH = Path("data/task4_train.jsonl")
VAL_BASE_PATH = Path("data/task4_val.jsonl")

TRAIN_OUTPUT_PATH = Path("data/task4_train_context_v2.jsonl")
VAL_OUTPUT_PATH = Path("data/task4_val_context_v2.jsonl")


MAX_CONTEXT_CHARS = 7000


def load_jsonl(path: Path):
    items = []

    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            if line.strip():
                items.append(json.loads(line))

    return items


def save_jsonl(path: Path, items):
    path.parent.mkdir(exist_ok=True)

    with open(path, "w", encoding="utf-8") as f:
        for item in items:
            f.write(json.dumps(item, ensure_ascii=False) + "\n")


def truncate_text(text: str, max_chars: int) -> str:
    if not isinstance(text, str):
        return ""

    text = text.strip()

    if len(text) <= max_chars:
        return text

    return text[:max_chars].rstrip() + "\n...[context truncated]"


def format_previous_queries(previous_queries):
    if not previous_queries:
        return "No previous queries."

    return "\n".join(
        f"{i + 1}. {query}"
        for i, query in enumerate(previous_queries)
    )


def build_prompt(item):
    research_question = item["research_question"]
    query_id = item["query_id"]
    previous_queries = item.get("previous_queries", [])
    visited_context = truncate_text(item.get("visited_context", ""), MAX_CONTEXT_CHARS)

    previous_queries_text = format_previous_queries(previous_queries)

    prompt = f"""You are a search-query planner for a DeepResearch agent.

The agent investigates a complex technical research question step by step.

You are given:
1. The original research question.
2. Descriptions of web sources that were already visited.
3. Previous search queries generated by the agent.

Your task is to generate exactly one next search query.

Important strategy:
- Do NOT generate a broad paraphrase of the research question.
- Use the visited sources to identify one concrete technical aspect that still deserves deeper search.
- Prefer source-specific terms: materials, mechanisms, process parameters, numerical conditions, industrial practices, equipment names, chemical species, failure modes, standards, trials, patents, or named companies.
- If previous queries already focus on one aspect, generate a query for a different aspect.
- Avoid repeating previous queries or simply combining their words.
- The query should look like something a researcher would type into Google Scholar, Semantic Scholar, or a technical search engine.
- The query should usually be 7-18 words.
- Return only the search query. No explanation.

Useful query patterns:
- mechanism + material + process condition
- equipment parameter + target effect + process name
- chemical species + slag/refractory interaction + temperature or process
- industrial practice + refractory protection + process
- company/product name + material + application
- numerical operating parameter + metallurgical outcome

Research question:
{research_question}

Current query step:
{query_id}

Visited sources context:
{visited_context}

Previous generated queries:
{previous_queries_text}

Generate one specific next search query:"""

    return prompt


def main():
    all_items = load_jsonl(INPUT_PATH)

    train_base = load_jsonl(TRAIN_BASE_PATH)
    val_base = load_jsonl(VAL_BASE_PATH)

    train_questions = set(item["research_question"] for item in train_base)
    val_questions = set(item["research_question"] for item in val_base)

    train_items = []
    val_items = []

    for item in all_items:
        item = item.copy()
        item["prompt"] = build_prompt(item)

        if item["research_question"] in val_questions:
            val_items.append(item)
        elif item["research_question"] in train_questions:
            train_items.append(item)
        else:
            raise ValueError(f"Unknown research question: {item['research_question']}")

    save_jsonl(TRAIN_OUTPUT_PATH, train_items)
    save_jsonl(VAL_OUTPUT_PATH, val_items)

    print("Saved train:", TRAIN_OUTPUT_PATH)
    print("Saved val:", VAL_OUTPUT_PATH)
    print("Train examples:", len(train_items))
    print("Val examples:", len(val_items))

    print()
    print("Prompt preview:")
    print(val_items[0]["prompt"][:3500])


if __name__ == "__main__":
    main()